# -*- coding: utf-8 -*-
CATS = [
 dict(slug="magasins", menu="Magasins", nom="Magasins bio", h1="Les meilleures <em>enseignes bio</em> en magasin",
  title="Meilleures enseignes bio en magasin 2026, comparatif et classement", 
  desc="Comparatif des enseignes bio en magasin, Biocoop, Naturalia, La Vie Claire, Carrefour Bio. Panier relevé en rayon, largeur de gamme, vrac, avis clients. Le classement 2026.",
  intro="Panier de 20 produits relevé en rayon, gammes comptées, vrac mesuré, avis Google lus. Nous classons les enseignes sur les mêmes critères.",
  hero="cat-magasins-hero.jpg", hero_alt="Rayon de fruits et légumes bio",
  subnav=["Fruits &amp; légumes","Vrac","Frais","Épicerie","Cosmétiques","Petits prix","Proximité"],
  count="4 comparatifs", une_h2="Le comparatif magasins à la une",
  grid_h2="Tous les comparatifs magasins bio",
  rank_h2="Le classement des enseignes bio en magasin en septembre 2026",
  rank_p="Note globale sur 10 sur les seuls magasins physiques. Le prix du panier et la largeur de gamme pèsent le plus.",
  rank=[("biocoop","Biocoop","Le plus large choix","Plus de 6 000 références, vrac partout, prix dans la moyenne.","8,3","up","▲ +0,2"),
        ("naturalia","Naturalia","Le plus urbain","Réseau dense en ville, gamme cosmétique forte, prix élevés.","7,6","flat","= 0,0"),
        ("la-vie-claire","La Vie Claire","Le plus régulier","Marque propre solide, magasins de taille moyenne.","7,4","up","▲ +0,1"),
        ("carrefour","Carrefour Bio","Le moins cher en ville","Panier serré, gamme courte, peu de vrac.","6,9","down","▼ -0,2"),
        ("generique","Marché de quartier","Le plus local","Producteurs directs, offre variable selon la saison.","6,5","flat","= 0,0")],
  cta_h2="Biocoop ou Naturalia pour vos courses ?", cta_p="Comparez deux enseignes sur nos cinq critères en un clic.",
  faq_h2="Questions fréquentes sur les magasins bio",
  faq=[("Quelle est la meilleure enseigne bio en magasin en 2026 ?","Sur nos relevés de septembre 2026, Biocoop obtient la meilleure note globale (8,3/10) grâce à la gamme la plus large et au vrac présent dans tous les magasins. Naturalia suit à 7,6."),
       ("Quelle enseigne bio est la moins chère ?","Carrefour Bio affiche le panier de 20 produits le plus bas en ville (54 €), Biocoop se place à 61 € et Naturalia à 68 €."),
       ("Où trouver le plus de vrac ?","Biocoop propose du vrac dans 100 % de ses magasins avec en moyenne 180 références, contre 90 chez La Vie Claire et 40 chez Naturalia."),
       ("Comment sont notées les enseignes ?","Cinq critères sur 10, prix du panier, largeur de gamme, proximité, avis clients et note globale pondérée. Les prix sont relevés en rayon hors promotion."),
       ("Les marchés valent-ils mieux qu'une enseigne bio ?","Pour les fruits et légumes de saison, souvent oui sur le prix. Pour l'épicerie, le frais et les cosmétiques, une enseigne garde l'avantage de la gamme.")],
  news_h2="Recevez chaque comparatif magasins avant tout le monde"),
 dict(slug="en-ligne", menu="En ligne", nom="Courses bio en ligne", h1="Les meilleurs <em>sites de courses bio</em>",
  title="Meilleurs sites de courses bio en ligne 2026, livraison et prix comparés",
  desc="Comparatif des sites de courses bio, Greenweez, Biocoop, La Fourche, Carrefour. Frais de livraison, délais, panier relevé, avis clients. Le classement 2026.",
  intro="Panier identique commandé sur chaque site, frais de port et délais relevés, avis Trustpilot lus. Nous classons les sites sur les mêmes critères.",
  hero="cat-en-ligne-hero.jpg", hero_alt="Livraison de courses à domicile",
  subnav=["Livraison","Frais de port","Abonnements","Vrac en ligne","Bébé","Petits prix","Drive"],
  count="3 comparatifs", une_h2="Le comparatif en ligne à la une",
  grid_h2="Tous les comparatifs courses bio en ligne",
  rank_h2="Le classement des sites de courses bio en septembre 2026",
  rank_p="Note globale sur 10 sur la vente en ligne. Les frais de livraison et le délai comptent autant que le prix.",
  rank=[("biocoop","Biocoop","Le retrait le plus rapide","Drive en magasin sous deux heures, livraison en ville.","8,0","up","▲ +0,3"),
        ("greenweez","Greenweez","Le plus large en ligne","12 000 références, livraison offerte dès 49 €.","7,8","flat","= 0,0"),
        ("carrefour","Carrefour","Le plus rapide en livraison","Créneaux le jour même, gamme bio courte.","7,1","flat","= 0,0"),
        ("leclerc","E.Leclerc","Le moins cher en drive","Panier bas, retrait gratuit, choix limité.","6,8","up","▲ +0,1"),
        ("la-vie-claire","La Vie Claire","Le plus simple","Site clair, livraison à 6,90 €.","6,4","down","▼ -0,1")],
  cta_h2="Greenweez ou Biocoop pour commander ?", cta_p="Comparez deux sites sur nos cinq critères en un clic.",
  faq_h2="Questions fréquentes sur les courses bio en ligne",
  faq=[("Quel est le meilleur site de courses bio en 2026 ?","Biocoop obtient 8,0/10 grâce au retrait en magasin sous deux heures et à un panier proche de celui du magasin. Greenweez suit à 7,8 avec la gamme la plus large."),
       ("Quel site bio livre gratuitement ?","Greenweez offre la livraison dès 49 € d'achat, Biocoop dès 60 € en ville, Carrefour à partir de 100 €."),
       ("Le drive bio est-il moins cher que la livraison ?","Oui, de 4 à 8 € par commande selon nos relevés, et le retrait chez E.Leclerc et Biocoop est gratuit sans minimum."),
       ("Comment sont notés les sites ?","Cinq critères sur 10, prix du panier livré, largeur de gamme, proximité et délais, avis clients, note globale pondérée."),
       ("Peut-on acheter du vrac en ligne ?","Greenweez et Biocoop proposent des formats vrac reconditionnés en sachets de 500 g à 5 kg, à un prix au kilo inférieur de 8 à 15 % au rayon.")],
  news_h2="Recevez chaque comparatif en ligne avant tout le monde"),
]
SUBIMG = {
 "magasins": {"Fruits &amp; légumes": "sub-legumes.jpg", "Vrac": "sub-vrac.jpg", "Frais": "sub-frais.jpg", "Épicerie": "sub-epicerie.jpg", "Cosmétiques": "sub-cosmetique.jpg", "Petits prix": "sub-prix.jpg", "Proximité": "sub-magasin.jpg"},
 "en-ligne": {"Livraison": "sub-livraison.jpg", "Frais de port": "sub-livraison.jpg", "Abonnements": "sub-epicerie.jpg", "Vrac en ligne": "sub-vrac.jpg", "Bébé": "sub-bebe.jpg", "Petits prix": "sub-prix.jpg", "Drive": "sub-magasin.jpg"},
}
